from __future__ import annotations

"""
QNG-CPU-032: P1 spectrum test — chi isolation in v3.

Tests the coupling topology of the v3 update law (DER-QNG-015) and
Prediction P1 from qng-chi-ontology-v1.md.

The v3 law has one cross-channel coupling: sigma → chi (one-way).
Chi does NOT feed back into sigma. Chi does NOT couple to phi.

Design:
  1. Build two quasi-static equilibrium backgrounds on a 64-node ring:
       Condition A: delta = 0.00 (Channel D off)
       Condition B: delta = 0.20 (Channel D on)
  2. Record equilibrium chi/sigma statistics and spatial power.
  3. Reset phi to a common random perturbation (frozen sigma/chi background).
  4. Run phi relaxation for 200 steps.
  5. Compare chi power, sigma power, and phi decay/power between conditions.

Expected outcome:
  - Chi IS generated by Channel D (check 1: chi mean differs)
  - Chi spatial power IS higher in B (check 2: chi power ratio > 10)
  - Sigma IS identical in A and B (check 3: sigma power null) — no chi→sigma feedback
  - Phi decay rate IS identical (check 4: phi tau null) — no chi→phi coupling
  - Phi spatial power IS identical (check 5: phi power null) — no chi→phi coupling

P1 (chi shifts phi spectrum) is a NULL result in v3 by construction.
This is an informative structural finding, not a defect.
"""

import json
import math
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT_DIR = ROOT / "07_validation" / "audits" / "qng-p1-spectrum-reference-v1"

# ---------------------------------------------------------------------------
# Parameters (shared with QNG-CPU-030 for consistency)
# ---------------------------------------------------------------------------

N_NODES: int = 64
EQ_STEPS: int = 3000
PHI_STEPS: int = 200
SEED: int = 20260325
PHI_SEED: int = 20260326  # independent seed for phi perturbation

SIGMA_REF: float = 0.5
SIGMA_SOURCE: float = 0.05
SOURCE_NODE: int = 0

ALPHA: float = 0.005
BETA: float = 0.35
CHI_DECAY: float = 0.005
CHI_REL: float = 0.35
PHI_REL: float = 0.20

DELTA_A: float = 0.00  # Condition A: no Channel D
DELTA_B: float = 0.20  # Condition B: Channel D active


# ---------------------------------------------------------------------------
# Graph
# ---------------------------------------------------------------------------

def build_ring(n: int) -> list[list[int]]:
    return [[(i - 1) % n, (i + 1) % n] for i in range(n)]


# ---------------------------------------------------------------------------
# Math helpers
# ---------------------------------------------------------------------------

def clip01(x: float) -> float:
    return max(0.0, min(1.0, x))


def wrap_angle(x: float) -> float:
    y = (x + math.pi) % (2.0 * math.pi) - math.pi
    return y if y > -math.pi else y + 2.0 * math.pi


def angle_diff(a: float, b: float) -> float:
    return wrap_angle(a - b)


def pearson(xs: list[float], ys: list[float]) -> float:
    n = len(xs)
    if n < 2:
        return 0.0
    mx = sum(xs) / n
    my = sum(ys) / n
    num = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    dx = math.sqrt(sum((x - mx) ** 2 for x in xs))
    dy = math.sqrt(sum((y - my) ** 2 for y in ys))
    if dx < 1e-15 or dy < 1e-15:
        return 0.0
    return num / (dx * dy)


# ---------------------------------------------------------------------------
# Quasi-static equilibration step (v3 with configurable delta)
# ---------------------------------------------------------------------------

def eq_step(
    sigma: list[float],
    chi: list[float],
    phi: list[float],
    adj: list[list[int]],
    delta: float,
) -> tuple[list[float], list[float], list[float]]:
    n = len(adj)
    new_sigma: list[float] = []
    new_chi: list[float] = []
    new_phi: list[float] = []

    for i, neighbors in enumerate(adj):
        sigma_i = sigma[i]
        chi_i = chi[i]
        phi_i = phi[i]

        sigma_neigh = sum(sigma[j] for j in neighbors) / len(neighbors)
        chi_neigh = sum(chi[j] for j in neighbors) / len(neighbors)
        sin_sum = sum(math.sin(phi[j]) for j in neighbors)
        cos_sum = sum(math.cos(phi[j]) for j in neighbors)
        phi_neigh = (
            math.atan2(sin_sum, cos_sum)
            if abs(sin_sum) + abs(cos_sum) > 1e-12
            else phi_i
        )

        sigma_new = clip01(
            sigma_i
            + ALPHA * (SIGMA_REF - sigma_i)
            + BETA * (sigma_neigh - sigma_i)
        )
        chi_new = (
            chi_i
            - CHI_DECAY * chi_i
            + CHI_REL * (sigma_neigh - sigma_i)
            + delta * (SIGMA_REF - sigma_i)   # Channel D (zero when delta=0)
        )
        phi_new = wrap_angle(phi_i + PHI_REL * angle_diff(phi_neigh, phi_i))

        new_sigma.append(sigma_new)
        new_chi.append(chi_new)
        new_phi.append(phi_new)

    # Clamp source
    new_sigma[SOURCE_NODE] = SIGMA_SOURCE
    return new_sigma, new_chi, new_phi


# ---------------------------------------------------------------------------
# Phi relaxation step with FROZEN sigma/chi background
# (tests whether background chi affects phi relaxation rate)
# ---------------------------------------------------------------------------

def phi_step_frozen(
    phi: list[float],
    adj: list[list[int]],
) -> list[float]:
    """
    Single phi relaxation step with no sigma/chi coupling.
    The phi channel in v3 is: phi_new = wrap(phi_i + PHI_REL * angle_diff(phi_bar, phi_i))
    Chi is NOT present in this channel — this is the null hypothesis test.
    """
    new_phi: list[float] = []
    for i, neighbors in enumerate(adj):
        phi_i = phi[i]
        sin_sum = sum(math.sin(phi[j]) for j in neighbors)
        cos_sum = sum(math.cos(phi[j]) for j in neighbors)
        phi_neigh = (
            math.atan2(sin_sum, cos_sum)
            if abs(sin_sum) + abs(cos_sum) > 1e-12
            else phi_i
        )
        new_phi.append(wrap_angle(phi_i + PHI_REL * angle_diff(phi_neigh, phi_i)))
    return new_phi


# ---------------------------------------------------------------------------
# Phi autocorrelation
# ---------------------------------------------------------------------------

def phi_autocorr_decay(phi_series: list[list[float]]) -> float:
    """
    Compute phi autocorrelation decay constant (in steps).
    Uses the mean phase deviation from the final state across all nodes.

    Returns tau_dec such that C(tau_dec) ≈ C(0)/e.
    If no decay is found, returns len(phi_series).
    """
    T = len(phi_series)
    n = len(phi_series[0])

    # Use final state as reference (equilibrium)
    phi_final = phi_series[-1]

    # Mean squared deviation from final state at each time
    dev = []
    for t in range(T):
        msd = sum(angle_diff(phi_series[t][i], phi_final[i]) ** 2 for i in range(n)) / n
        dev.append(msd)

    c0 = dev[0]
    if c0 < 1e-15:
        return 0.0

    threshold = c0 / math.e
    for tau in range(T):
        if dev[tau] <= threshold:
            return float(tau)

    return float(T)


# ---------------------------------------------------------------------------
# Spatial power spectrum (DFT magnitude squared, summed)
# ---------------------------------------------------------------------------

def spatial_power(values: list[float]) -> float:
    """
    Total spatial power: sum of |DFT coefficients|² for k>0.
    For a ring of N nodes: DFT_k = sum_j values[j] * exp(-2pi*i*k*j/N)
    """
    n = len(values)
    power = 0.0
    for k in range(1, n // 2 + 1):
        re = sum(values[j] * math.cos(2 * math.pi * k * j / n) for j in range(n))
        im = sum(values[j] * math.sin(2 * math.pi * k * j / n) for j in range(n))
        power += re * re + im * im
    return power / n


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_condition(
    adj: list[list[int]],
    rng: random.Random,
    delta: float,
) -> dict:
    """Run equilibration and phi relaxation for one delta value."""
    # Initialize state
    sigma = [SIGMA_REF + 0.02 * rng.uniform(-1, 1) for _ in range(N_NODES)]
    sigma[SOURCE_NODE] = SIGMA_SOURCE
    chi = [0.0] * N_NODES
    phi = [rng.uniform(-0.1, 0.1) for _ in range(N_NODES)]

    # Equilibrate sigma/chi/phi
    for _ in range(EQ_STEPS):
        sigma, chi, phi = eq_step(sigma, chi, phi, adj, delta)

    # Record equilibrium statistics
    chi_mean = sum(chi) / N_NODES
    chi_var = sum((c - chi_mean) ** 2 for c in chi) / N_NODES
    sigma_mean = sum(sigma) / N_NODES
    sigma_var = sum((s - sigma_mean) ** 2 for s in sigma) / N_NODES

    sigma_power = spatial_power(sigma)
    chi_power = spatial_power(chi)

    # Reset phi to common random perturbation (same phi_rng for both conditions)
    phi_rng = random.Random(PHI_SEED)
    phi = [phi_rng.uniform(-math.pi, math.pi) for _ in range(N_NODES)]

    # Run phi relaxation with FROZEN sigma/chi background
    phi_series: list[list[float]] = [phi[:]]
    for _ in range(PHI_STEPS):
        phi = phi_step_frozen(phi, adj)
        phi_series.append(phi[:])

    # Phi statistics at equilibrium (final state)
    phi_final = phi_series[-1]
    phi_power = spatial_power(phi_final)

    # Phi autocorrelation decay constant
    tau_dec = phi_autocorr_decay(phi_series)

    return {
        "chi_mean": chi_mean,
        "chi_var": chi_var,
        "chi_spatial_power": chi_power,
        "sigma_mean": sigma_mean,
        "sigma_var": sigma_var,
        "sigma_spatial_power": sigma_power,
        "phi_spatial_power": phi_power,
        "phi_tau_dec": tau_dec,
    }


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(
        description="QNG-CPU-032: P1 spectrum test — chi-tension effect on phi dynamics."
    )
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    adj = build_ring(N_NODES)

    # Run both conditions with identical seeds
    rng_a = random.Random(SEED)
    rng_b = random.Random(SEED)

    print("Running Condition A (delta=0.00)...")
    cond_a = run_condition(adj, rng_a, DELTA_A)
    print("Running Condition B (delta=0.20)...")
    cond_b = run_condition(adj, rng_b, DELTA_B)

    # ------------------------------------------------------------------
    # Check 1: chi tension confirmed
    # ⟨χ⟩_B > ⟨χ⟩_A + 0.10
    # ------------------------------------------------------------------
    chi_diff = cond_b["chi_mean"] - cond_a["chi_mean"]
    check1_pass = chi_diff > 0.10

    # ------------------------------------------------------------------
    # Check 2: chi spatial power increases with Channel D
    # P_chi_B / P_chi_A > 10.0 (if P_chi_A < 1e-6, check P_chi_B > 1.0 instead)
    # ------------------------------------------------------------------
    p_chi_a = cond_a["chi_spatial_power"]
    p_chi_b = cond_b["chi_spatial_power"]
    if p_chi_a > 1e-6:
        chi_power_ratio = p_chi_b / p_chi_a
        check2_pass = chi_power_ratio > 10.0
    else:
        chi_power_ratio = float("inf") if p_chi_b > 1.0 else 0.0
        check2_pass = p_chi_b > 1.0

    # ------------------------------------------------------------------
    # Check 3: sigma spatial power UNCHANGED (null — no chi→sigma feedback)
    # |P_sigma_B / P_sigma_A − 1| < 0.01
    # ------------------------------------------------------------------
    if cond_a["sigma_spatial_power"] > 1e-15:
        sigma_power_ratio = cond_b["sigma_spatial_power"] / cond_a["sigma_spatial_power"]
        sigma_power_null_diff = abs(sigma_power_ratio - 1.0)
    else:
        sigma_power_ratio = 1.0
        sigma_power_null_diff = 0.0
    check3_pass = sigma_power_null_diff < 0.01

    # ------------------------------------------------------------------
    # Check 4: phi relaxation rate NULL — decay constants should be equal
    # |τ_B − τ_A| / τ_A < 0.10
    # ------------------------------------------------------------------
    tau_a = cond_a["phi_tau_dec"]
    tau_b = cond_b["phi_tau_dec"]
    if tau_a > 1e-9:
        tau_rel_diff = abs(tau_b - tau_a) / tau_a
    else:
        tau_rel_diff = 0.0 if abs(tau_b - tau_a) < 1e-9 else 1.0
    check4_pass = tau_rel_diff < 0.10

    # ------------------------------------------------------------------
    # Check 5: phi spatial power unchanged (phase sector unaffected)
    # |P_phi_B − P_phi_A| / P_phi_A < 0.15
    # ------------------------------------------------------------------
    if cond_a["phi_spatial_power"] > 1e-15:
        phi_power_rel_diff = abs(cond_b["phi_spatial_power"] - cond_a["phi_spatial_power"]) / cond_a["phi_spatial_power"]
    else:
        phi_power_rel_diff = 0.0
    check5_pass = phi_power_rel_diff < 0.15

    # ------------------------------------------------------------------
    # Aggregate
    # ------------------------------------------------------------------
    checks = {
        "chi_tension_confirmed_pass": check1_pass,
        "chi_power_ratio_pass": check2_pass,
        "sigma_power_null_pass": check3_pass,
        "phi_decay_null_pass": check4_pass,
        "phi_power_null_pass": check5_pass,
    }
    decision = all(checks.values())

    interpretation = (
        "chi modulates amplitude sector only (sigma affected, phi unaffected in v3). "
        "Chi-to-phi channel is absent in v3. "
        "P1 as stated requires a direct chi→phi coupling for the phase sector."
        if decision
        else "Unexpected result — see individual check results."
    )

    report = {
        "test_id": "QNG-CPU-032",
        "decision": "pass" if decision else "fail",
        "parameters": {
            "n_nodes": N_NODES,
            "eq_steps": EQ_STEPS,
            "phi_steps": PHI_STEPS,
            "alpha": ALPHA,
            "beta": BETA,
            "delta_a": DELTA_A,
            "delta_b": DELTA_B,
            "sigma_source": SIGMA_SOURCE,
        },
        "condition_a": {k: round(v, 6) for k, v in cond_a.items()},
        "condition_b": {k: round(v, 6) for k, v in cond_b.items()},
        "comparisons": {
            "chi_mean_diff": round(chi_diff, 6),
            "chi_power_ratio": round(chi_power_ratio if chi_power_ratio != float("inf") else 9999.0, 6),
            "sigma_power_null_diff": round(sigma_power_null_diff, 6),
            "phi_tau_rel_diff": round(tau_rel_diff, 6),
            "phi_power_rel_diff": round(phi_power_rel_diff, 6),
        },
        "checks": checks,
        "interpretation": interpretation,
    }

    (out_dir / "report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    summary_lines = [
        "# QNG P1 Spectrum Reference v1",
        "",
        f"- decision: `{'pass' if decision else 'fail'}`",
        "",
        "## Conditions",
        f"- Condition A: delta={DELTA_A}  (Channel D off)",
        f"- Condition B: delta={DELTA_B}  (Channel D on)",
        "",
        "## Check 1: chi tension confirmed",
        f"- ⟨χ⟩_A={cond_a['chi_mean']:.4f}  ⟨χ⟩_B={cond_b['chi_mean']:.4f}",
        f"- diff={chi_diff:.4f}  threshold > 0.10  {'PASS' if check1_pass else 'FAIL'}",
        "",
        "## Check 2: chi spatial power increases with Channel D",
        f"- P_chi_A={cond_a['chi_spatial_power']:.4f}  P_chi_B={cond_b['chi_spatial_power']:.4f}",
        f"- ratio={chi_power_ratio if chi_power_ratio != float('inf') else '∞'!s}  threshold > 10.0  {'PASS' if check2_pass else 'FAIL'}",
        "",
        "## Check 3: sigma spatial power UNCHANGED (expected null — no chi→sigma feedback)",
        f"- P_sigma_A={cond_a['sigma_spatial_power']:.4f}  P_sigma_B={cond_b['sigma_spatial_power']:.4f}",
        f"- |ratio-1|={sigma_power_null_diff:.4f}  threshold < 0.01  {'PASS' if check3_pass else 'FAIL'}",
        "",
        "## Check 4: phi relaxation rate NULL (expected)",
        f"- τ_dec_A={tau_a:.2f}  τ_dec_B={tau_b:.2f}",
        f"- relative diff={tau_rel_diff:.4f}  threshold < 0.10  {'PASS' if check4_pass else 'FAIL'}",
        f"  Interpretation: {'phi dynamics independent of chi background (no chi→phi coupling in v3)' if check4_pass else 'WARNING: phi dynamics differ — indirect chi→phi path detected'}",
        "",
        "",
        "## Check 5: phi spatial power NULL (expected)",
        f"- P_phi_A={cond_a['phi_spatial_power']:.4f}  P_phi_B={cond_b['phi_spatial_power']:.4f}",
        f"- relative diff={phi_power_rel_diff:.4f}  threshold < 0.15  {'PASS' if check5_pass else 'FAIL'}",
        "",
        "## Interpretation",
        interpretation,
    ]
    (out_dir / "summary.md").write_text("\n".join(summary_lines) + "\n", encoding="utf-8")

    print(f"qng_p1_spectrum_reference: {'PASS' if decision else 'FAIL'}")
    print((out_dir / "report.json").as_posix())
    return 0 if decision else 1


if __name__ == "__main__":
    raise SystemExit(main())
