from __future__ import annotations

"""Phi xi scan vs GAMMA_PHI (QNG-GPU-013, GPU).

If phi mass is generated by Channel F back-reaction (Einstein suggestion):
  m_phi_eff ~ sqrt(GAMMA_PHI)  =>  xi ~ 1/sqrt(GAMMA_PHI)

Test: run phi mass probe at 4 GAMMA_PHI values, fit xi from disorder profile.
  GAMMA_PHI in {0.03, 0.05, 0.10, 0.20}

If xi(g1)/xi(g2) ~ sqrt(g2/g1):   MASSIVE_PHI (self-generated gap)
If xi approximately constant:       MASSLESS_PHI (xi from geometry, not Channel F)

Uses L=60 for speed (enough bulk range without r=80 contamination).
Fits only r in [R+5, L/2-8] to avoid periodic images.
"""

import json
import math
from pathlib import Path

import cupy as cp
import numpy as np
from scipy.optimize import curve_fit

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT_DIR = ROOT / "07_validation" / "audits" / "qng-phi-xi-scan-v1"

SIGMA_REF = 0.5
ALPHA     = 0.005
BETA      = 0.35
BETA_PHI  = 0.02
DELTA_CHI = 0.20
CHI_DECAY = 0.020
CHI_REL   = 0.35

PHASE1 = 300
PHASE2 = 1500

L      = 60
R_RING = 5
LAMBDA_SCREEN = math.sqrt(BETA / ALPHA)  # 8.37 lu

GAMMA_VALUES = [0.03, 0.05, 0.10, 0.20]


def build_nb(L):
    xs = np.arange(L, dtype=np.int32)
    xg, yg, zg = np.meshgrid(xs, xs, xs, indexing='ij')
    xg = xg.ravel(); yg = yg.ravel(); zg = zg.ravel()
    nb = np.stack([
        ((xg-1)%L)*L*L + yg*L + zg, ((xg+1)%L)*L*L + yg*L + zg,
        xg*L*L + ((yg-1)%L)*L + zg,  xg*L*L + ((yg+1)%L)*L + zg,
        xg*L*L + yg*L + (zg-1)%L,    xg*L*L + yg*L + (zg+1)%L,
    ], axis=1).astype(np.int32)
    return cp.asarray(nb)


def build_phi_ring(L, R):
    cx = cy = cz = L / 2.0
    xs = np.arange(L, dtype=np.float64)
    xg, yg, zg = np.meshgrid(xs, xs, xs, indexing='ij')
    dx = xg-cx; dy = yg-cy; dz = zg-cz
    for d in [dx, dy, dz]:
        d[:] = np.where(d >  L/2, d-L, d)
        d[:] = np.where(d < -L/2, d+L, d)
    rho = np.sqrt(dx*dx + dy*dy)
    return cp.asarray(np.arctan2(dz, rho-R).ravel())


def build_shells(L):
    cx = cy = cz = L / 2.0
    xs = np.arange(L, dtype=np.float64)
    xg, yg, zg = np.meshgrid(xs, xs, xs, indexing='ij')
    dx = xg-cx; dy = yg-cy; dz = zg-cz
    for d in [dx, dy, dz]:
        d[:] = np.where(d >  L/2, d-L, d)
        d[:] = np.where(d < -L/2, d+L, d)
    r = np.sqrt(dx*dx + dy*dy + dz*dz).ravel()
    n_shells = L // 2
    shells = [cp.asarray((r >= s) & (r < s+1)) for s in range(n_shells)]
    return shells, np.arange(n_shells) + 0.5


def wrap_gpu(a):
    a = a % (2*math.pi)
    return cp.where(a > math.pi, a - 2*math.pi, a)

def nb_mean(f, nb): return f[nb].mean(axis=1)

def disorder_gpu(phi, nb):
    pnb = phi[nb]
    return cp.maximum(0.0, 1.0 - cp.sqrt(cp.cos(pnb).mean(axis=1)**2 +
                                          cp.sin(pnb).mean(axis=1)**2))

def phi_wm(phi, sm, nb):
    pnb = phi[nb]; snb = sm[nb]; tw = snb.sum(axis=1)
    sx = (snb*cp.cos(pnb)).sum(axis=1); sy = (snb*cp.sin(pnb)).sum(axis=1)
    return cp.where(tw>1e-10, cp.arctan2(sy/cp.maximum(tw,1e-10),
                                          sx/cp.maximum(tw,1e-10)), phi)

def step1(sm, chi, phi, nb):
    smb = nb_mean(sm, nb)
    nsm = cp.clip(sm + ALPHA*(SIGMA_REF-sm) + BETA*(smb-sm), 0.0, 1.0)
    nc  = chi*(1-CHI_DECAY) + CHI_REL*(smb-sm) + DELTA_CHI*(SIGMA_REF-sm)
    np_ = wrap_gpu(phi + BETA_PHI*wrap_gpu(phi_wm(phi,sm,nb)-phi))
    return nsm, nc, np_

def step2(sm, chi, phi, nb, gamma_phi):
    smb = nb_mean(sm, nb)
    dis = disorder_gpu(phi, nb)
    nsm = cp.clip(sm + ALPHA*(SIGMA_REF-sm) + BETA*(smb-sm)
                     - gamma_phi*dis*sm, 0.0, 1.0)
    nc  = chi*(1-CHI_DECAY) + CHI_REL*(smb-sm) + DELTA_CHI*(SIGMA_REF-sm)
    np_ = wrap_gpu(phi + BETA_PHI*wrap_gpu(phi_wm(phi,sm,nb)-phi))
    return nsm, nc, np_


def measure_dis_profile(phi, sm, nb, shells):
    dis = disorder_gpu(phi, nb)
    profile = []
    for mask in shells:
        n = float(cp.sum(mask))
        if n < 1:
            profile.append(0.0)
            continue
        profile.append(float(cp.sum(dis * mask)) / n)
    return np.array(profile)


def fit_exp_powerlaw(r_vals, dis_vals):
    """Fit both exponential and power law. Return (xi, alpha, better_fit)."""
    mask = dis_vals > 1e-10
    r_fit = r_vals[mask]; d_fit = dis_vals[mask]
    if len(r_fit) < 4:
        return None, None, None, None, None

    # Exponential
    try:
        def exp_model(r, A, xi): return A * np.exp(-r / xi)
        popt_e, _ = curve_fit(exp_model, r_fit, d_fit,
                               p0=[d_fit[0], LAMBDA_SCREEN],
                               bounds=([0, 0.1], [1, 200]), maxfev=5000)
        A_e, xi_e = popt_e
        res_e = d_fit - exp_model(r_fit, A_e, xi_e)
        ss_e = np.sum(res_e**2)
    except Exception:
        xi_e = None; ss_e = np.inf

    # Power law (log-log linear)
    try:
        log_r = np.log(r_fit); log_d = np.log(d_fit)
        coeffs = np.polyfit(log_r, log_d, 1)
        alpha_p = -coeffs[0]; A_p = math.exp(coeffs[1])
        res_p = d_fit - A_p * r_fit**(-alpha_p)
        ss_p = np.sum(res_p**2)
    except Exception:
        alpha_p = None; ss_p = np.inf

    # R² for both
    ss_tot = np.sum((d_fit - d_fit.mean())**2) + 1e-20
    r2_e = 1 - ss_e/ss_tot if xi_e is not None else None
    r2_p = 1 - ss_p/ss_tot if alpha_p is not None else None

    better = None
    if r2_e is not None and r2_p is not None:
        better = "exp" if r2_e > r2_p + 0.02 else ("power" if r2_p > r2_e + 0.02 else "ambiguous")

    return xi_e, r2_e, alpha_p, r2_p, better


def run_gamma(gamma_phi, nb, shells, r_centers, phi_init):
    N = L*L*L
    sm  = cp.full(N, SIGMA_REF, dtype=cp.float64)
    chi = cp.zeros(N, dtype=cp.float64)
    phi = phi_init.copy()

    for _ in range(PHASE1): sm, chi, phi = step1(sm, chi, phi, nb)
    for _ in range(PHASE2): sm, chi, phi = step2(sm, chi, phi, nb, gamma_phi)

    profile = measure_dis_profile(phi, sm, nb, shells)

    # Fit bulk: r in [R+5, L/2-5]
    r_min = R_RING + 5
    r_max = L//2 - 5
    mask  = (r_centers > r_min) & (r_centers < r_max)
    r_fit = r_centers[mask]
    d_fit = profile[mask]

    xi, r2_e, alpha, r2_p, better = fit_exp_powerlaw(r_fit, d_fit)

    M_ring = float(N*SIGMA_REF - cp.sum(cp.maximum(0.0, SIGMA_REF - sm)))

    return {
        "gamma_phi": gamma_phi,
        "xi": round(xi, 3) if xi else None,
        "r2_exp": round(r2_e, 4) if r2_e else None,
        "alpha": round(alpha, 3) if alpha else None,
        "r2_pow": round(r2_p, 4) if r2_p else None,
        "better": better,
        "M_ring": round(M_ring, 1),
        "profile": [round(float(d), 8) for d in profile],
    }


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    args = ap.parse_args()
    out = Path(args.out_dir); out.mkdir(parents=True, exist_ok=True)

    print("Phi xi scan vs GAMMA_PHI (QNG-GPU-013)")
    print(f"L={L}, R={R_RING}, lambda_screen={LAMBDA_SCREEN:.2f} lu")
    print(f"GAMMA_PHI values: {GAMMA_VALUES}")
    print(f"Prediction (massive phi): xi ~ 1/sqrt(GAMMA_PHI)")
    print(f"  => xi ratios: {[round(math.sqrt(GAMMA_VALUES[0]/g), 3) for g in GAMMA_VALUES]}")
    print()

    dev = cp.cuda.Device(0)
    print(f"GPU: device 0, free mem = {dev.mem_info[0]/1e9:.2f} GB\n")

    nb = build_nb(L)
    shells, r_centers = build_shells(L)
    phi_init = build_phi_ring(L, R_RING)

    results = []
    for gamma in GAMMA_VALUES:
        print(f"GAMMA_PHI = {gamma}...", flush=True)
        res = run_gamma(gamma, nb, shells, r_centers, phi_init)
        results.append(res)
        xi_str   = f"{res['xi']:.3f}" if res["xi"] else "?"
        r2e_str  = f"{res['r2_exp']:.4f}" if res["r2_exp"] else "?"
        alpha_str = f"{res['alpha']:.3f}" if res["alpha"] else "?"
        r2p_str  = f"{res['r2_pow']:.4f}" if res["r2_pow"] else "?"
        print(f"  M_ring={res['M_ring']:.1f}  xi={xi_str} lu  R2_exp={r2e_str}  "
              f"alpha={alpha_str}  R2_pow={r2p_str}  better={res['better']}", flush=True)

    print()
    print("="*70)
    print("XI vs GAMMA_PHI — MASSIVE vs MASSLESS TEST")
    print("="*70)
    print(f"{'gamma':>7}  {'xi_fit':>8}  {'xi_pred*':>9}  {'alpha':>7}  "
          f"{'R2_exp':>7}  {'R2_pow':>7}  {'better':>10}")
    print(f"  (* predicted if xi ~ 1/sqrt(gamma), normalized to gamma=0.10)")
    print("-"*70)

    ref = next((r for r in results if abs(r["gamma_phi"]-0.10) < 0.001), results[0])
    xi_ref = ref["xi"] or 1.0

    for res in results:
        g = res["gamma_phi"]
        xi_pred = xi_ref * math.sqrt(0.10 / g)
        xi_str  = f"{res['xi']:.3f}" if res["xi"] else "?"
        a_str   = f"{res['alpha']:.3f}" if res["alpha"] else "?"
        r2e_str = f"{res['r2_exp']:.4f}" if res["r2_exp"] else "?"
        r2p_str = f"{res['r2_pow']:.4f}" if res["r2_pow"] else "?"
        print(f"  {g:>5.2f}  {xi_str:>8}  {xi_pred:>9.3f}  {a_str:>7}  "
              f"{r2e_str:>7}  {r2p_str:>7}  {str(res['better']):>10}")

    # Check if xi ~ 1/sqrt(gamma)
    xi_vals   = [r["xi"] for r in results if r["xi"] is not None]
    g_vals    = [r["gamma_phi"] for r in results if r["xi"] is not None]
    alpha_vals = [r["alpha"] for r in results if r["alpha"] is not None]

    print()
    if len(xi_vals) >= 3:
        # Fit log(xi) vs log(gamma) -> slope should be -0.5 if massive
        log_g = np.log(g_vals); log_xi = np.log(xi_vals)
        slope, intercept = np.polyfit(log_g, log_xi, 1)
        print(f"log(xi) vs log(gamma) slope = {slope:.3f}  (expected -0.5 if massive phi)")

        if abs(slope + 0.5) < 0.15:
            phi_verdict = "MASSIVE_PHI"
            phi_detail  = f"xi ~ gamma^({slope:.2f}) consistent with 1/sqrt(gamma) -> Channel F generates m_phi"
        elif abs(slope) < 0.10:
            phi_verdict = "MASSLESS_PHI"
            phi_detail  = f"xi approximately constant (slope={slope:.2f}) -> phi gapless, L=20 is coincidence"
        else:
            phi_verdict = "AMBIGUOUS"
            phi_detail  = f"slope={slope:.2f} between 0 (massless) and -0.5 (massive)"

        print(f"\nVERDICT: {phi_verdict}")
        print(f"  {phi_detail}")
    else:
        slope = None
        phi_verdict = "INSUFFICIENT_DATA"
        phi_detail  = "not enough successful xi fits"
        print(f"VERDICT: {phi_verdict}")

    if len(alpha_vals) >= 3:
        alpha_mean = np.mean(alpha_vals)
        alpha_std  = np.std(alpha_vals)
        print(f"\nPower-law alpha: mean={alpha_mean:.3f}  std={alpha_std:.3f}")
        print(f"  (vortex ring in 3D: expected alpha=2; constant alpha -> massless)")

    report = {
        "params": {"L": L, "R_RING": R_RING, "LAMBDA_SCREEN": LAMBDA_SCREEN,
                   "BETA_PHI": BETA_PHI, "GAMMA_VALUES": GAMMA_VALUES},
        "results": [{k: v for k, v in r.items() if k != "profile"} for r in results],
        "xi_slope": round(slope, 4) if slope is not None else None,
        "verdict": phi_verdict, "detail": phi_detail,
    }
    with open(out/"report.json", "w") as f: json.dump(report, f, indent=2)

    lines = ["# Phi Xi Scan vs GAMMA_PHI (QNG-GPU-013)", "",
             f"L={L}, R={R_RING}, lambda_screen={LAMBDA_SCREEN:.2f}", "",
             "| gamma_phi | xi (lu) | xi_pred (1/sqrt) | alpha | R2_exp | R2_pow | better |",
             "|-----------|---------|-----------------|-------|--------|--------|--------|"]
    for res in results:
        g = res["gamma_phi"]
        xi_pred = (xi_ref * math.sqrt(0.10/g)) if res["xi"] else 0
        lines.append(f"| {g} | {res['xi'] or '?'} | {xi_pred:.2f} | "
                     f"{res['alpha'] or '?'} | {res['r2_exp'] or '?'} | "
                     f"{res['r2_pow'] or '?'} | {res['better'] or '?'} |")
    lines += ["", f"## Verdict: {phi_verdict}", "", phi_detail]
    (out/"summary.md").write_text("\n".join(lines)+"\n", encoding="utf-8")
    print(f"\nArtifacts: {out}")
    return 0 if phi_verdict in ("MASSIVE_PHI", "MASSLESS_PHI") else 1


if __name__ == "__main__":
    raise SystemExit(main())
